name: artroom-ldm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - git
  - python=3.9
  - cudatoolkit=11.6
  - pytorch=1.12.1
  - pip=22.2.2
  - numpy=1.23.3
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - pip:
    - -r requirements.txt